version: "3"

services:
  hls-proxy:
    build: .
    ports:
      - 443:443
    volumes:
      - <cert path>:/app/tls/cert.pem
      - <key path>:/app/tls/key.pem
    command: npm start -- --tls-cert /app/tls/cert.pem --tls-key /app/tls/key.pem